export const cities = [
  {
    id: 'houston',
    name: 'Houston',
    state: 'Texas',
    hero: require('./Houston-Skyline-Sunset-1.webp'),
  },
  {
    id: 'chicago',
    name: 'Chicago',
    state: 'Illinois',
    hero: require('./Chicago-Ground-View.avif'),
  },
  {
    id: 'new-york',
    name: 'New York',
    state: 'New York',
    hero: require('./Time-Square.avif'),
  },
];

export const hotels = [
  {
    id: 'houston-1',
    cityId: 'houston',
    name: 'The Westin Dowtown Houston',
    neighborhood: 'East Downtown',
    rating: 4.4,
    reviewCount: 1190,
    price: 320,
    nights: 2,
    image: require('./The-Westin-Downtown.webp'),
    room: 'King/Queen Room',
    perk: 'Skyline view',
  },
  {
    id: 'houston-2',
    cityId: 'houston',
    name: 'Holiday Inn',
    neighborhood: 'Jacinto City',
    rating: 4.5,
    reviewCount: 834,
    price: 159,
    nights: 1,
    image: require('./Holiday-Inn.avif'),
    room: 'Standard Room',
    perk: 'Free Breakfast & Wifi',
  },
  {
    id: 'chicago-1',
    cityId: 'chicago',
    name: 'The Penisula Chicago',
    neighborhood: 'Streeterville',
    rating: 9.3,
    reviewCount: 2800,
    price: 650,
    nights: 1,
    image: require('./Penisula-Chicago.jpg'),
    room: 'Surpior Room',
    perk: 'House Car Services',
  },
  {
    id: 'chicago-2',
    cityId: 'chicago',
    name: 'AC Hotel',
    neighborhood: 'River North',
    rating: 8.8,
    reviewCount: 1900,
    price: 180,
    nights: 1,
    image: require('./AC-Hotel.jpg'),
    room: 'Classic Room',
    perk: 'Accommodations',
  },
  {
    id: 'new-york-1',
    cityId: 'new-york',
    name: 'EVEN Hotel',
    neighborhood: 'Midtown Manhattan',
    rating: 8.5,
    reviewCount: 1000,
    price: 180,
    nights: 3,
    image: require('./EVEN-Hotel.avif'),
    room: 'Standard Room',
    perk: 'Athletic Zone',
  },
  {
    id: 'new-york-2',
    cityId: 'new-york',
    name: 'PUBLIC Hotel',
    neighborhood: 'Nolita & SoHo',
    rating: 8.1,
    reviewCount: 1000,
    price: 300,
    nights: 1,
    image: require('./Public-Hotel.webp'),
    room: 'King Room',
    perk: 'City Views',
  },
];
